This application is perfect for compiling kernel or package, it was designed by creating a shell-script holding the configure __OPT__ && make clean && make  where __OPT__ stand for all CFLAGS, LDFLAGS and option from configure with  ---enable-..., --with-... it run the file after you save it and if the compilation or the return statement is OK, it store Your file as-is inside a file-storage compressed where function like DataExtractionTool should revert the compressed information into a working script, ready to repeat the operation before you have changed thing you did not have idea or did not note it. It's also perfect for template compilation (C++ templating) who require severe ajustement from compiler notice in bjam-file can be inserted in a script where the bjam-file can be generated by the script and saving the script is a clever and conventionnal way to save space and information at once.
This script also comming with a --stopservices switche where after specifying the UUID instance inside prefixed-variable LSSUUIDInstance or Unified UUID reserved prefixed-variable UUID, it will terminate the execution-loop  This method can also allow starting multiple instance at once . Later a ZenityStopServices can be explain to filter application from same family and not using DoCtrlHandler / ActivatSeServerBuffer which depend from their own methodology .

diff --git a/_sub_Function_Appliance b/_sub_Function_Appliance
--- a/_sub_Function_Appliance
+++ b/_sub_Function_Appliance
@@ -33,7 +33,7 @@
 ###  - Many more precautions and tests. 
 ### 
 
-if [ ${versionGPI:=0.0.2} == "0.0.1" ] ; then 
+if [ ${versionGPI:=0.0.2} == "0.0.2" ] ; then 
  
  unset GnrlPrsrInfctr; 
  function GnrlPrsrInfctr()
@@ -700,3 +700,355 @@ if [ ${versionGPI:=0.0.2} == "0.0.1" ] ; then
 
 
 fi
+
+### function LoopShellScript 
+
+### Is not actually ready in design plan it only miss couple of function like 
+### DataExtractionTool which requiert to extract compressed file and transcoded 
+### in base64 to hold on the same line of SHA1SUM, before pushing it to version 
+### 0.0.2
+
+### In General:
+### 
+### This application is perfect for compiling kernel or package, it was designed
+### by creating a shell-script holding the configure __OPT__ && make clean && make  
+### where __OPT__ stand for all CFLAGS, LDFLAGS and option from configure with 
+### ---enable-..., --with-... it run the file after you save it and if the compilation
+### or the return statement is OK, it store Your file as-is inside a file-storage
+### compressed where function like DataExtractionTool should revert the compressed 
+### information into a working script, ready to repeat the operation before you
+### have changed thing you did not have idea or did not note it. It's also perfect 
+### for template compilation (C++ templating) who require severe ajustement from 
+### compiler notice in bjam-file can be inserted in a script where the bjam-file 
+### can be generated by the script and saving the script is a clever and 
+### conventionnal way to save space and information at once. 
+### 
+### This script also comming with a --stopservices switche where after specifying 
+### the UUID instance inside prefixed-variable LSSUUIDInstance or Unified UUID
+### reserved prefixed-variable UUID, it will terminate the execution-loop  
+### This method can also allow starting multiple instance at once . Later a 
+### ZenityStopServices can be explain to filter application from same family
+### and not using DoCtrlHandler / ActivatSeServerBuffer which depend from their
+### own methodology .
+### 
+### example : 
+### >>> To stop a running instance called 25d4a256-9c1a-11e6-8b1d-001e4c8856d6 
+### you can call it like : 
+### 
+### UUID=25d4a256-9c1a-11e6-8b1d-001e4c8856d6 LoopShellScript --stopservices
+### or 
+### LSSUUIDInstance=25d4a256-9c1a-11e6-8b1d-001e4c8856d6 LoopShellScript --stopservices
+### 
+
+
+if [ ${versionLSS:=0.0.1} == "0.0.1" ] ; then 
+ 
+ unset LoopShellScript GetSha1Sum ; 
+ function LoopShellScript()
+ {
+   function Verbosis()
+  {
+   local -a ArrayArg=( $* ) ;
+   local -a __call_locality=( Verb Verbosis ) ; 
+   local Arg0=${ArrayArg[0]} ; 
+   local StrMsg=${VerbMsg:=__TEXT__} ; 
+   local StrDevOut=${VerbDev:=/dev/stderr} ; 
+   local IsVerboseState=${VerbState:=False} ;
+   local StrVerboseHeader=${VerbHeader:=VERBOSE} ;
+   local IsEvalRequiredForm=${VerbEvalForm:=False} ; 
+   local IsDisplayFormatted=${VerbFormated:=True} ;
+   local IsAppendMode=${VerbAppendDev:=False} ; 
+   local IsExtendedOutput=${VerbExtendedOut:=False} ; 
+   local ArrayArg=( $* ) ; 
+   if [ "${IsVerboseState:=False}" == "True" ] ; then 
+    if [ "${IsDisplayFormatted:=True}" == "True" ] ; then 
+     if [ "${IsAppendMode:=False}" == "True" ] ; then 
+       echo -ne "${StrVerboseHeader}:[ ${StrMsg} ]\n" >> ${StrDevOut} ;
+     else  
+       echo -ne "${StrVerboseHeader}:[ ${StrMsg} ]\n" > ${StrDevOut} ;
+     fi
+    else
+     if [ "${IsEvalRequiredForm:=False}" == "True" ] ; then 
+      if [ "${IsExtendedOutput:False}" == "True" ] ; then 
+        echo -ne "${StrMsg}" ;  
+      else
+        echo "${StrMsg}" ;  
+      fi
+     else
+      if [ "${IsAppendMode:=False}" == "True" ] ; then 
+       if [ "${IsExtendedOutput:False}" == "True" ] ; then 
+         echo -ne "${StrMsg}" >> ${StrDevOut} ;
+       else
+         echo "${StrMsg}" >> ${StrDevOut} ;
+       fi
+      else
+       if [ "${IsExtendedOutput:False}" == "True" ] ; then 
+        echo -ne "${StrMsg}" > ${StrDevOut} ;
+       else
+        echo "${StrMsg}" > ${StrDevOut} ;
+       fi 
+      fi
+     fi 
+    fi 
+   fi
+  } 
+  ### Model :VerbMsg=MSG VerbHeader=DEBUG VerbEvalForm=False VerbFormated=True VerbState=True VerbDev=/dev/stderr  Verbosis
+
+   if [ ${versionCA:=0.0.0} == "0.0.0" ] ; then 
+    local __call_locality=( LSS LoopShellScript ) ;
+    local ArrayArg=( $* ) ;
+    local Arg0=${ArrayArg[0]} ; 
+    local StrParentApps=${__call_locality[1]} ;
+    local StrStartMain=${GSUFuncStart:=__main_StartServices} ; 
+   elif [ ${versionCA:=0.0.0} == "0.0.1" ] ; then 
+    eval $( eval CAFunctName=LoopShellScript CAIsAddParent=False __Call_Argument ) ; 
+   elif [ ${versionCA:=0.0.0} == "0.0.2" ] ; then 
+    eval $( eval CAFunctName=LoopShellScript CAIsAddParent=False CallArgument ) ;
+   fi  
+  
+   local StrStartFile=${LSSFileName:=start-configure.sh} ; 
+   local StrStoreResult=${LSSFileStorage:=.LoopShellScript} ; 
+   local StrDateFormat=${LSSDateFormat:='%Y%m%d-%H:%M:%S'} ; 
+   local StrPathLoopState=${LSSLoopFile:=/var/cache/Fnct.D/Loop-LSS-__UUID__} ; 
+   local StrUUIDInstance=${LSSUUIDInstance:=Last-instance-UUID};
+   local StrShaSumExtract=${LSSSHAIndexExtract:=None} ; 
+   local StrDefaultFileFormat=${LSSFileFormat:=BZIP2+BASE64} ;
+   local BoolIsExtraction=${LSSIsExtraction:=False} ; 
+   local BoolHideAppsDebug=${LSSIsHideScriptOutput:=False} ; 
+   ### A short-cut to call uniformely an UUID used by this Application. 
+   local UUID=${UUID:=${StrUUIDInstance}} ; 
+   local StrTemplateShaStorage="__DATE__ __SHA__ __FILENAME__ __FORMAT__ __FILECONTENT__" ;
+   
+   local StrVarList="BoolHideAppsDebug,StrVarList,StrStartFile,StrStoreResult,StrDateFormat,StrPathLoopState,StrUUIDInstance,StrTemplateShaStorage,StrDefaultFileFormat,StrShaSumExtract,BoolIsExtraction"
+   
+   function GetSha1Sum()
+   {
+    sha1sum ${GSSFileName} | cut -d ' ' -f 1 ; 
+   } 
+
+   function GetFileFormatCmd( )
+   {
+    if [ ${versionCA:=0.0.0} == "0.0.0" ] ; then 
+     local __call_locality=( GFFC GetFileFormatCmd ) ;
+     local ArrayArg=( $* ) ;
+     local Arg0=${ArrayArg[0]} ; 
+     local StrParentApps=${__call_locality[1]} ;
+    elif [ ${versionCA:=0.0.0} == "0.0.1" ] ; then 
+     eval $( eval CAFunctName=GetFileFormatCmd CAIsAddParent=True __Call_Argument ) ; 
+    elif [ ${versionCA:=0.0.0} == "0.0.2" ] ; then 
+     eval $( eval CAFunctName=GetFileFormatCmd CAIsAddParent=True CallArgument ) ;
+    fi  
+    
+   }
+   function DataExtractionTool()
+   {
+    if [ ${versionCA:=0.0.0} == "0.0.0" ] ; then 
+     local __call_locality=( DET DataExtractionTool ) ;
+     local ArrayArg=( $* ) ;
+     local Arg0=${ArrayArg[0]} ; 
+     local StrParentApps=${__call_locality[1]} ;
+    elif [ ${versionCA:=0.0.0} == "0.0.1" ] ; then 
+     eval $( eval CAFunctName=DataExtractionTool CAIsAddParent=True __Call_Argument ) ; 
+    elif [ ${versionCA:=0.0.0} == "0.0.2" ] ; then 
+     eval $( eval CAFunctName=DataExtractionTool CAIsAddParent=True CallArgument ) ;
+    fi  
+    
+    ### Extraction Tool not ready....
+    
+   } 
+   function ShellControlServices()
+   {
+    if [ ${versionCA:=0.0.0} == "0.0.0" ] ; then 
+     local __call_locality=( SCS ShellControlServices ) ;
+     local ArrayArg=( $* ) ;
+     local Arg0=${ArrayArg[0]} ; 
+     local StrParentApps=${__call_locality[1]} ;
+    elif [ ${versionCA:=0.0.0} == "0.0.1" ] ; then 
+     eval $( eval CAFunctName=LoopShellScript CAIsAddParent=True __Call_Argument ) ; 
+    elif [ ${versionCA:=0.0.0} == "0.0.2" ] ; then 
+     eval $( eval CAFunctName=LoopShellScript CAIsAddParent=True CallArgument ) ;
+    fi  
+    local StrUUID=$( GetUAppsRegisterName=LoopShellScript GetUTimeBased=True GetULoop=False GetUUID ) ; 
+    StrPathLoopState=${StrPathLoopState//__UUID__/${StrUUID}}
+    VerbMsg="Instance ID:${StrUUID}" VerbHeader=DEBUG VerbEvalForm=False VerbFormated=True VerbState=True VerbDev=/dev/stderr  Verbosis ;
+    touch ${StrPathLoopState} ; 
+
+    local -A ArrayCompiler  ; 
+    local StrCurrentSha ; 
+    local IntCompileState=0 ; 
+    local IntCompileAdd=0 ;  
+    local IntReturn=0 ; 
+    local IntFindCompiler ; 
+    local StrScriptCpr ; 
+    local StrDate ;
+    
+    while [ -f ${StrPathLoopState} ] ; do 
+     StrCurrentSha=$( GSSFileName=${StrStartFile} GetSha1Sum ) ; 
+
+     IntFindCompiler=0 ; 
+     for Iter in ${!ArrayCompiler[@]} ; do 
+       if [ "${Iter}" == "${StrCurrentSha}" ] ; then 
+         IntFindCompiler=1 ; 
+       fi ; 
+     done 
+    
+     if [ ${IntFindCompiler:=0} -eq 0 ] ; then 
+       ### Must add a sha1sum for specific change of compiler directive inside 
+       ### start-configure.sh
+       ArrayCompiler[${StrCurrentSha}]="UNKNOW" ; 
+     fi 
+     
+     if [ "${ArrayCompiler[${StrCurrentSha}]}" == "UNKNOW" ] ; then 
+      ### Do find a sha1sum compiler directive differ from previous version . 
+      ### run the script and report it execution state, because the Compiler 
+      ### directive are empty. 
+      echo -ne "Add command-directive, SHA1SUM:${StrCurrentSha}, status: ${ArrayCompiler[${StrCurrentSha}]}\n"  ; 
+      IntCompileAdd=1 ;
+      IntFindCompiler=0 ;
+      sleep 5 ; 
+     elif [ "${ArrayCompiler[${StrCurrentSha}]}" == "OK" ] ; then 
+      echo -ne "Shell-Script SHA1SUM:${StrCurrentSha}, ${ArrayCompiler[${StrCurrentSha}]}\n" ;
+      IntCompileAdd=0 ; 
+      IntFindCompiler=0 ;
+     elif [ "${ArrayCompiler[${StrCurrentSha}]}" == "FAILED" ] ; then 
+      echo -ne "Shell-Script SHA1SUM:${StrCurrentSha}, ${ArrayCompiler[${StrCurrentSha}]}\n" ;
+      IntCompileAdd=0 ; 
+      IntFindCompiler=0 ;
+     fi
+
+     if [ ${IntCompileAdd:=0} -eq 1  ] ; then 
+       if [ "${BoolHideAppsDebug:=False}" == "True" ] ; then 
+        . ${StrStartFile} 2>&1 > /dev/null  ;
+       else
+         . ${StrStartFile} ;
+       fi
+       IntReturn=$? ;
+       echo -ne "Shell-Script returned state: ${IntReturn}\n" ; 
+       IntCompileState=1 ;  
+       IntCompileAdd = 0 ; 
+     else
+      if [ "${ArrayCompiler[${StrCurrentSha}]}" != "UNKNOW" ] ; then 
+        echo -ne "Shell-Script classified:${StrCurrentSha},\n\tdon't required to start over.\n"
+      fi 
+      sleep 5; 
+      StrDate=$( GODFormat="${StrDateFormat}" GetOtherDate ) ; 
+      echo -ne "UUID-Instance:${StrUUID}\nDate:${StrDate}\n"
+      echo -ne "Shell-scripts directive result:\n" ;
+      for StrDirective in ${!ArrayCompiler[@]} ; do
+       if [ "${ArrayCompiler[${StrDirective}]}" != "UNKNOW" ] ; then 
+         echo -ne "Shell-Script SHA1SUM:${StrDirective}, result: ${ArrayCompiler[${StrDirective}]}\n" ; 
+       fi 
+      done ;
+      echo -ne "------------------------------------------------------------------------\n\n" ; 
+     fi 
+     
+     if [ ${IntCompileState:=0} -eq 1  ] ; then 
+      ### Time to analyse the result of shell-script 
+      if [ ${IntReturn:=0} -eq 0  ] ; then 
+       ArrayCompiler[${StrCurrentSha}]="OK"
+       StrScriptCpr=$( cat ${StrStartFile} | bzip2 -9c | base64 --wrap=0 ) ; 
+       StrNewParserInfo=${StrTemplateShaStorage} ; 
+       
+       StrDate=$( GODFormat="${StrDateFormat}" GetOtherDate ) ; 
+          
+       StrNewParserInfo=${StrNewParserInfo//__DATE__/${StrDate}}
+       StrNewParserInfo=${StrNewParserInfo//__SHA__/${StrCurrentSha}}
+       StrNewParserInfo=${StrNewParserInfo//__FILENAME__/${StrStartFile}}
+       StrNewParserInfo=${StrNewParserInfo//__FORMAT__/${StrDefaultFileFormat}}
+       StrNewParserInfo=${StrNewParserInfo//__FILECONTENT__/${StrScriptCpr}}
+       echo -ne "${StrNewParserInfo}\n" >> ${StrStoreResult} ; 
+      else 
+       ### Many state can be returned, like script from configure will return :
+       ### configure: error: C compiler cannot create executables, 
+       ### and return code == 77 .
+       ArrayCompiler[${StrCurrentSha}]="FAILED"
+      fi 
+      IntCompileState=0;
+      IntReturn=0; 
+     fi   
+    done ; 
+    
+   }
+
+   function __main_StopServices()
+   {
+    if [ ${versionCA:=0.0.0} == "0.0.0" ] ; then 
+     local __call_locality=( Main __main_StopServices ) ;
+     local ArrayArg=( $* ) ;
+     local Arg0=${ArrayArg[0]} ; 
+    elif [ ${versionCA:=0.0.0} == "0.0.1" ] ; then 
+     eval $( eval CAFunctName=__main_StopServices CAIsAddParent=True __Call_Argument ) ;
+    elif [ ${versionCA:=0.0.0} == "0.0.2" ] ; then 
+     eval $( eval CAFunctName=__main_StopServices CAIsAddParent=True CallArgument ) ;
+    fi 
+
+    local StrUUID=${UUID};
+    if [ "${StrUUID:=None}" == "None" ] ; then 
+     StrUUID=${StrUUIDInstance} ; 
+    fi 
+    local StrPathLoopState=${StrPathLoopState//__UUID__/${StrUUID}} ; 
+    VerbMsg="Shutdown Instance ID:${StrUUID}, file: ${StrPathLoopState}" VerbHeader=DEBUG VerbEvalForm=False VerbFormated=True VerbState=True VerbDev=/dev/stderr  Verbosis ;
+    if [ -f ${StrPathLoopState} ] ; then 
+     rm -f ${StrPathLoopState} ; 
+    fi 
+   }
+   
+   function __main_StartServices()
+   {
+    if [ ${versionCA:=0.0.0} == "0.0.0" ] ; then 
+     local __call_locality=( CFCD CurlFtpContentDownload ) ;
+     local ArrayArg=( $* ) ;
+     local Arg0=${ArrayArg[0]} ; 
+    elif [ ${versionCA:=0.0.0} == "0.0.1" ] ; then 
+     eval $( eval CAFunctName=__main_StartServices CAIsAddParent=True __Call_Argument ) ;
+    elif [ ${versionCA:=0.0.0} == "0.0.2" ] ; then 
+     eval $( eval CAFunctName=__main_StartServices CAIsAddParent=True CallArgument ) ;
+    fi 
+   
+    local StrCmdAction=$( BVTIdType=4 BVTIsPreambule=False BVTIsValueToVarAssert=True BVTBoolVarName=\${BoolIsExtraction:=False} BVTBoolCase=False BVTVTVVarA=${StrVarList} BVTVTFnctA=ShellControlServices  BoolVarTest ; BVTIdType=5 BVTIsPreambule=False BVTIsValueToVarAssert=True BVTVTFnctA=DataExtractionTool BVTVTVVarA=${StrVarList}  BoolVarTest ) ; 
+    eval ${StrCmdAction} ; 
+   }
+   
+   local StrSwitchMessages="${StrSwitchesShow}${StrStartSwitches}\n${StrStopSwitches}\n${StrGetMsgSwitches}\n${StrListMsgSwitches}\n${StrCompWordMsgSwitches}\n" ;
+   local StrNameHelper="LoopShellScript\t\tA Test-Unit to test command with many directive to test and report the working solution.";
+   local StrSummary="This application does survey your script and run-it belong to a different SHA1SUM reported by the application and upon a result it store-it inside a File for working solution. " ; 
+   local StrSynopsis="This application is also perfect for Shell-Script with TAG to replace or add directive. Coming with Start and Stop services, it expect to produce execution once and store the file inside file with SHA1SUM header from your script qualified of different from previous save or modification. Result is compressed and this application will deliver a method to extract the compressed file inside this SHA1SUM header. (END OF DRAFT INFORMATION)";
+   local StrDescription="A common way to use it is to test your source package requiring to change the configure with multiples option some may fail and require to change the information inside. This application will wait until the file is changed and report you if it work or not. File Specified by the application is compressing the working result ready to extract the working solution. This Application can be shutdown from a command from same USER by using --stopservices function. It require to specify a Uniform Ressource Identifier specified inside prefixed-variable, LSSUUIDInstance. Also UUID variable can be used instead. By starting a new instance of this application it show you a UUID identifier and a new file inside  prefixed-variable LSSLoopFile will exist the time the loop is testing and compiling succesfull script. Stopping the services will only remove the file and stop the Loop. (END OF DRAFT INFORMATION)" ;
+   
+   
+   if [ "${Arg0:=--startservices}" == "--help"	] ; then 
+    GVRIsName=True GVRIsSummary=True GVRIsSynopsis=True GVRIsDesc=True GetVarReference ${__call_locality[1]} ; 
+    echo -ne "${StrSwitchMessages}" > /dev/stderr ; 
+   elif [ "${Arg0:=--startservices}" == "--get" ] ; then 
+    eval """local ArgGet=\${${ArrayArg[1]}}""" ; 
+    echo -ne """${ArgGet}\n""" ;
+   elif [ "${Arg0:=--startservices}" == "--list" ] ; then 
+    eval $( __GetVarReferenceList ) ;	
+   elif [ "${Arg0:=--startservices}" == "--stopservices" ] ; then 
+    eval $( eval \
+      VTVIsArrayStyleInsert=True  \
+      VTVValueEntry=${StrVarList} \
+      VTVIsValueReAssign=True     \
+      VTVIsValueToConvert=False   \
+      VTVIsWhiteList=True         \
+      VTVWhiteListTransfert=UUID  \
+      ValueToVariable ) __main_StopServices ; 
+   elif [ "${Arg0:=--startservices}" == "--startservices" ] ; then 
+    StrMsg="Application:${__call_locality[1]} , version:( versionVTV:__VER_VTV__, versionCA:__VER_CA__, versionBVT:__VER_BVT__)" ; 
+    StrMsg=${StrMsg//__VER_CA__/${versionCA}} ;
+    StrMsg=${StrMsg//__VER_VTV__/${versionVTV}} ;
+    StrMsg=${StrMsg//__VER_BVT__/${versionBVT}} ;
+    VerbMsg=${StrMsg} VerbHeader="VERSION" VerbEvalForm=False VerbFormated=True VerbState=True VerbDev=/dev/stderr  Verbosis ; 
+    VerbMsg="Entry in function ${StrStartMain}" VerbHeader="${__call_locality[1]}-DEBUG" VerbEvalForm=False VerbFormated=True VerbState=${BoolDisplayDebug} VerbDev=/dev/stderr  Verbosis ; 
+    eval $( eval \
+      VTVIsArrayStyleInsert=True  \
+      VTVValueEntry=${StrVarList} \
+      VTVIsValueReAssign=True     \
+      VTVIsValueToConvert=False   \
+      ValueToVariable ) ${StrStartMain}
+   fi  
+ }
+
+### end-if versionLSS
+fi 
+
